CREATE TABLE Usuário (
  id_usuario NUMBER NOT NULL,
  nome VARCHAR2(200) NOT NULL,
  PRIMARY KEY (id_usuario)
);
             
CREATE TABLE Funcionario (
  id_funcionario NUMBER(38) NOT NULL,
  matricula VARCHAR2(100) UNIQUE NOT NULL,
  PRIMARY KEY (id_funcionario),
  CONSTRAINT FK_USUARIO
    FOREIGN KEY (id_funcionario)
      REFERENCES Usuário(id_usuario)
);

CREATE TABLE Cliente (
  id_cliente NUMBER(38) NOT NULL,
  cpf VARCHAR2(14) UNIQUE NOT NULL,
  telefone VARCHAR2(14) NOT NULL,
  endereço VARCHAR2(200) NOT NULL,
  PRIMARY KEY (id_cliente),
  CONSTRAINT FK_USUARIO_CLIENTE
    FOREIGN KEY (id_cliente)
      REFERENCES Usuário(id_usuario)
);
DROP TABLE ALUGUEL 

CREATE TABLE Aluguel (
  id_aluguel NUMBER(38) NOT NULL,
  id_cliente NUMBER(38) NOT NULL,
  id_carro NUMBER(38) NOT NULL,
  diaDoAluguel DATE NOT NULL,
  diaDaEntrega DATE NOT NULL,
  PRIMARY KEY (id_aluguel),
  CONSTRAINT FK_Cliente_Aluguel
    FOREIGN KEY (id_cliente)
      REFERENCES Cliente(id_cliente)
);

DROP TABLE CARRO;

CREATE TABLE Carro (
  id_carro NUMBER(38) NOT NULL,
  id_aluguel NUMBER(38) NOT NULL,
  alugado CHAR(1),
  nome VARCHAR2(200) NOT NULL,
  marca VARCHAR2(200) NOT NULL,
  classe CHAR(1) NOT NULL,
  quantidade_passageiros NUMBER(38) NOT NULL,
  km_rodados NUMBER(38) NOT NULL,
  valor_diaria DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (id_carro),
  CONSTRAINT FK_ALUGUEL_Carro
    FOREIGN KEY (id_aluguel)
      REFERENCES Aluguel(id_aluguel)
);


CREATE SEQUENCE VEM_SER.SEQ_USUARIO
START WITH 1
INCREMENT BY 1
nocache nocycle;

CREATE SEQUENCE VEM_SER.SEQ_FUNCIONARIO
START WITH 1
INCREMENT BY 1
nocache nocycle;

CREATE SEQUENCE VEM_SER.SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
nocache nocycle;

CREATE SEQUENCE VEM_SER.SEQ_ALUGUEL
START WITH 1
INCREMENT BY 1
nocache nocycle;

CREATE SEQUENCE VEM_SER.SEQ_CARRO
START WITH 1
INCREMENT BY 1
nocache nocycle;

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'João');

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'Paulo');

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'William');

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'Pedro');

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'Ana Barbara');

INSERT INTO VEM_SER.USUÁRIO
(ID_USUARIO, NOME)
VALUES(seq_usuario.nextval, 'Maria');

INSERT INTO VEM_SER.FUNCIONARIO
(ID_FUNCIONARIO, MATRICULA)
VALUES(seq_funcionario.nextval, '12141');

INSERT INTO VEM_SER.FUNCIONARIO
(ID_FUNCIONARIO, MATRICULA)
VALUES(seq_funcionario.nextval, '12142');

INSERT INTO VEM_SER.FUNCIONARIO
(ID_FUNCIONARIO, MATRICULA)
VALUES(seq_funcionario.nextval, '12143');

INSERT INTO VEM_SER.FUNCIONARIO
(ID_FUNCIONARIO, MATRICULA)
VALUES(seq_funcionario.nextval, '12144');

INSERT INTO VEM_SER.CLIENTE
(ID_CLIENTE, CPF, TELEFONE, ENDEREÇO)
VALUES(seq_cliente.nextval, '000.000.000-00', '(61)99999-9999', 'Rua Presidente Dutra, 09, Centro');

INSERT INTO VEM_SER.CLIENTE
(ID_CLIENTE, CPF, TELEFONE, ENDEREÇO)
VALUES(seq_cliente.nextval, '000.000.000-11', '(61)99999-9998', 'Rua Presidente Dutra, 154, Bairro Maria Cândida');

INSERT INTO VEM_SER.CLIENTE
(ID_CLIENTE, CPF, TELEFONE, ENDEREÇO)
VALUES(seq_cliente.nextval, '000.000.000-22', '(61)99999-9997', 'Avenida Antônio Carlos Guimarães, 154A, Centro');

INSERT INTO VEM_SER.CLIENTE
(ID_CLIENTE, CPF, TELEFONE, ENDEREÇO)
VALUES(seq_cliente.nextval, '000.000.000-33', '(61)99999-9996', 'Avenida Boolevard, apartamento 1001, Parque dos Viajantes');

INSERT INTO VEM_SER.CLIENTE
(ID_CLIENTE, CPF, TELEFONE, ENDEREÇO)
VALUES(seq_cliente.nextval, '000.000.000-44', '(61)99999-9995', 'Avenida das Flores');


INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 1, 1, '30/06/2022', '02/07/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 1, 2, '10/06/2022', '15/06/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 2, 4, '30/06/2022', '02/07/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 3, 9, '30/06/2022', '02/07/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 4, 6, '30/06/2022', '02/07/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 2, 6, '30/06/2022', '02/07/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 5, 7, '15/06/2022', '18/06/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 3, 8, '18/06/2022', '20/06/2022');

INSERT INTO VEM_SER.ALUGUEL
(ID_ALUGUEL, ID_CLIENTE, ID_CARRO, DIADOALUGUEL, DIADAENTREGA)
VALUES(seq_aluguel.nextval, 2, 3, '18/06/2022', '20/06/2022');


INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 1, 'S', 'Pálio', 'Fiat', 'C', 5, 20000, 100);


INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 2, 'S', 'Gol', 'Volkswagen', 'C', 5, 25000, 100);


INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 3, 'F', 'Onix', 'Chevrolet', 'C', 5, 30000, 100);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 4, 'S', 'Compass', 'Jeep', 'B', 5, 10000, 300);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 5, 'S', 'Civic', 'Honda', 'B', 5, 10000, 300);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 6, 'F', 'T-Cross', 'Volkswagen', 'B', 5, 15000, 300);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 7, 'S', 'Elegance', 'Mercedes-Benz', 'A', 5, 20000, 500);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 8, 'S', '911 GTS', 'Porsche', 'A', 5, 5000, 1000);

INSERT INTO VEM_SER.CARRO
(ID_CARRO, ID_ALUGUEL, ALUGADO, NOME, MARCA, CLASSE, QUANTIDADE_PASSAGEIROS, KM_RODADOS, VALOR_DIARIA)
VALUES(seq_carro.nextval, 9, 'F', 'Shelby GT500', 'Mustang', 'A', 5, 5000, 500);


SELECT * FROM ALUGUEL
SELECT * FROM CLIENTE
SELECT * FROM CARRO
SELECT * FROM FUNCIONARIO
SELECT * FROM usuário